### PR TITLE
Added salt to hashes

### PR DESCRIPTION
**Pull request by williamhatcher**

### CODE REVIEW

**Comment by williamhatcher** [comment]
@WandererJackalope can you test this locally?
We just need to ensure creating a player works and logging in works.

**Comment by WandererJackalope** [comment]
I'll test it early tomorrow morning. Sometime around 9 and I'll get back to y'all.
Though I'm pretty sure I will need to know the db uri. Where would I find that?

**Comment by WandererJackalope** [comment]
Tested asking if a test user was created
username: test

**Comment by WandererJackalope** [comment]
successfully are able to create a user like this

**Review by WandererJackalope — APPROVED** [review]
Successfully are able to create a user with the salt

**Pull request merged**
